INSERT INTO `references` (`id`, `title`, `author`, `univali`, `doi`, `pmid`) VALUES
(1, 'Chemical Constituents of Calophyllum brasiliense. 2. Structure of Three New Coumarins and Cancer Chemopreventive Activity of 4-Substituted Coumarins', 'Chihiro Ito, Masataka Itoigawa, Yoshitaka Mishina, Valdir Cechinel Filho, Fumio Enjo, Harukuni Tokuda, Hoyoku Nishino, Hiroshi Furukawa', b'1', '10.1021/np0203640', '12662094'),
(2, 'A new triterpene with antinociceptive activity from Maytenus robusta', 'Rivaldo Niero , Ana P Mafra, Ana C Lenzi, Valdir Cechinel-Filho, Cesar A Tischer, Angela Malheiros, Marcia M De Souza, Rosendo A Yunes, Franco Delle Monache', b'1', '10.1080/14786410601101951', '17393657'),
(3, 'Three New Triterpenes from the Resinous Bark of Protium kleinii and their Antinociceptive Activity', 'Fabiana V. Lima, Angela Malheiros, Michel F. Otuki, João B. Calixto, Rosendo A. Yunes, Valdir Cechinel Filho, Franco Delle Monache', b'1', '10.1590/S0103-50532005000400014', NULL),
(4, 'Sorocein L and Sorocein M: Two Diels-Alder Type Adducts from Sorocea ilicifolia', 'Franco Ferrari, Valdir Cechinel Filho, Tiziana Cabras, Irene Messana', b'1', '10.1021/np020515z', '12713424'),
(5, 'Phytochemical Analysis and Antinociceptive Properties of the Seeds of Garcinia achachairu', 'Marlova Manhabosco Dal Molin, Suellen Silva, Douglas Rafael Alves, Nara Lins Meira Quintão, Franco Delle Monache, Valdir Cechinel Filho, Rivaldo Niero', b'1', '10.1007/s12272-012-0405-3', '22553054'),
(6, 'Evaluation of the anti-proliferative effect the extracts of Allamanda blanchetti and A. schottii on the growth of leukemic and endothelial cell', 'Dionezine de F Navarro Schmidt, Rosendo A Yunes, Estela H Schaab, Angela Malheiros, Valdir Cechinel Filho, Gilberto C Franchi Jr, Alexandre E Nowill, Angelo A Cardoso, José A Yunes', b'1', NULL, '16959189'),
(7, 'I3-naringenin-II8-4’-OMe-eriodictyoI: a New Potential Analgesie Agent Isolated from Rheedia gardneriana Leaves', 'V Cechinel Filho, K L da Silva, M M de Souza, A E Oliveira, R A Yunes, C L Guimarães, L G Verdi, E L Simionatto, F Delle Monache', b'1', '10.1515/znc-2000-9-1024', '11098837'),
(8, 'A New Naphthoquinone Isolated from the Bulbs of Cipura paludosa and Pharmacological Activity of Two Main Constituents', 'Priscila Batista Tessele, Franco Delle Monache, Nara Lins Meira Quintão, Gislaine Francieli da Silva, Lilian Wunsch Rocha, Greice M R S Lucena, Vania M M Ferreira, Rui D S Prediger, Valdir Cechinel Filho', b'1', '10.1055/s-0030-1250745', '21283955'),
(10, 'Cytotoxic, Antitumour and Antimetastatic Activity of Two New Polyacetylenes Isolated from Vernonia scorpioides (Lam.) Pers', 'Juliana B. Klein, Alexandre E. Nowill, Gilberto C. Franchi Jr, Maique W. Biavatti, Nara L.M. Quintão, Rilton A. de Freitas', b'1', '10.1111/bcpt.12098', '23763911'),
(11, 'Macrocarpal-like Compounds from Eugenia umbelliflora Fruits and Their Antibacterial Activity', 'Larissa Gabriela Faqueti, Ingrid Vicente Farias, Elem Cristina Sabedot , Franco Delle Monache, Arturo San Feliciano, Ivânia Teresinha Albrecht Schuquel, Valdir Cechinel-Filho, Alexandre Bella Cruz, Christiane Meyre-Silva', b'1', '10.1021/acs.jafc.5b03562', '26308768'),
(12, 'Chemical Constituents of Calophyllum brasiliensis: Structure Elucidation of Seven New Xanthones and Their Cancer Chemopreventive Activity 1', 'Chihiro Ito, Masataka Itoigawa, Yoshitaka Mishina, Valdir Cechinel Filho, Teruo Mukainaka, Harukuni Tokuda, Hoyoku Nishino, Hiroshi Furukawa', b'1', '10.1021/np010398s', '11908963'),
(14, 'Limonoids from the Endemic Brazilian Species Raulinoa echinata', 'M W Biavatti, P C Vieira, M F da Silva, J B Fernandes, S Albuquerque', b'1', '10.1515/znc-2001-7-815', '11531091'),
(15, 'Pharmacological and phytochemical investigations of different parts of Calophyllum brasiliense (Clusiaceae)', 'D E B Isaias, R Niero, V F Noldin, F de Campos-Buzzi, R A Yunes, F Delle-Monache, V Cechinel-Filho', b'1', NULL, '15587592 ');